# Generated by Django 5.2.1 on 2025-08-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='addres',
            field=models.TextField(blank=True, null=True),
        ),
    ]
